config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :api do
    resources :todos, only: [:create, :update, :destroy] do
      delete 'destroy_all', on: :collection
    end
  end

  resources :home, only: :index
end

app/models/todo.rb
class Todo
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::TaggableOn

  taggable_on :tags

  field :text, type: String
  field :status, type: String

  validates_presence_of [:text, :status]

  scope :listed, -> { where(status: 'listed') }
  scope :doing, -> { where(status: 'doing') }
  scope :done, -> { where(status: 'done') }
end

app/controllers/api/todos_controller.rb
module API
  class TodosController < ApiController
    def create
      todo = Todo.create!(todo_params)
      render json: todo.to_json, status: 201
    end

    def update
      todo = Todo.find(params[:id])
      todo.status = params[:status]
      todo.save!
      render json: todo.to_json, status: 200
    end

    def destroy
      todo = Todo.find(params[:id])
      todo.destroy
      render json: {}, status: 204
    end

    def destroy_all
      todo = Todo.where(status: params[:status])
      todo.destroy
      render json: {}, status: 204
    end

    private

    def todo_params
      params.require(:todo).permit(:text).merge(status: params[:status])
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout :use_xhr?

  def use_xhr?
    false if request.xhr?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home_presenter = HomePresenter.new
    render locals: { listed: @home_presenter.listed,
                     doing: @home_presenter.doing,
                     done: @home_presenter.done }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_doing.slim
- unless doing.count.zero?
  - doing.each do |item|
    li.collection-item
      = link_to '<i class="mdi-navigation-close grey-text" id="move_to_doing"></i>'.html_safe, api_todo_path(item), class: "tooltipped delete-list", data: { remote: true, tooltip: "Remove", delay: 10 }, method: :delete
      = item.text
      = link_to '<i class="mdi-navigation-arrow-forward pink-text text-darken-4" id="move_to_doing"></i>'.html_safe, api_todo_path(id: item, status: "done"), class: "secondary-content tooltipped move_to", data: { remote: true, tooltip: "Move to done", delay: 10 }, method: :patch
      = link_to '<i class="mdi-navigation-arrow-back pink-text text-darken-4" id="move_to_doing"></i>'.html_safe, api_todo_path(id: item, status: "listed"), class: "secondary-content tooltipped move_to", data: { remote: true, tooltip: "Move to 'To DOs'", delay: 10 }, method: :patch

app/views/home/_done.slim
- unless done.count.zero?
  - done.each do |item|
    li.collection-item
      = link_to '<i class="mdi-navigation-close grey-text" id="move_to_doing"></i>'.html_safe, api_todo_path(item), class: "tooltipped delete-list", data: { remote: true, tooltip: "Remove", delay: 10 }, method: :delete
      = item.text
      = link_to '<i class="mdi-navigation-arrow-back pink-text text-darken-4" id="move_to_doing"></i>'.html_safe, api_todo_path(id: item, status: "doing"), class: "secondary-content tooltipped move_to", data: { remote: true, tooltip: "Move to doing", delay: 10 }, method: :patch

app/views/home/_listed.slim
- unless listed.count.zero?
  - listed.each do |item|
    li.collection-item
      = link_to '<i class="mdi-navigation-close grey-text" id="move_to_doing"></i>'.html_safe, api_todo_path(item), class: "tooltipped delete-list", data: { remote: true, tooltip: "Remove", delay: 10 }, method: :delete
      = item.text
      = link_to '<i class="mdi-navigation-arrow-forward pink-text text-darken-4" id="move_to_doing"></i>'.html_safe, api_todo_path(id: item, status: "doing"), class: "secondary-content tooltipped move_to", data: { remote: true, tooltip: "Move to doing", delay: 10 }, method: :patch

app/views/home/_todos_row.slim
.row
  .col.s4
    ul.collection.with-header.z-depth-1
      li.collection-header
        h6.pink-text.text-darken-3 To DOs
        .row
          .col.s6
            small = "#{pluralize(listed.count, 'item')} on To DOs"
          .col.s6.right-align
            small
              = link_to "Clear All", "#", class: "pink-text text-darken-4", id: "clear-all-listed"
      = form_tag "/api/todos", id: "todo_form", class: "white", remote: true
        .input-field.col.s12
          = text_field_tag "todo[text]", "", placeholder: "Add new list"
          = hidden_field_tag "status", "listed"
      = render partial: "home/listed", locals: { listed: listed }
  .col.s4
    ul.collection.with-header.z-depth-1
      li.collection-header
        h6.pink-text.text-darken-3 Doing
        .row
          .col.s6
            small = "#{pluralize(doing.count, 'item')} on Doing"
          .col.s6.right-align
            small
              = link_to "Clear All", "#", class: "pink-text text-darken-4", id: "clear-all-doing"
      = render partial: "home/doing", locals: { doing: doing }

  .col.s4
    ul.collection.with-header.z-depth-1
      li.collection-header
        h6.pink-text.text-darken-3 Done
        .row
          .col.s6
            small = "#{pluralize(done.count, 'item')} on Done"
          .col.s6.right-align
            small
              = link_to "Clear All", "#", class: "pink-text text-darken-4", id: "clear-all-done"
      = render partial: "home/done", locals: { done: done }

app/views/home/index.slim
h1.center.pink-text.text-darken-4 To DOs
= render partial: "home/todos_row", locals: { listed: listed, doing: doing, done: done }


javascript:
  $(document).ready(function() {
    on_form_submit();
    move_to_doing();
    refresh_when_remove();
    $('.tooltipped').tooltip({delay: 20});
    $("#clear-all-done").click(function(){
      Materialize.toast('<span>Are you sure?</span><a class="btn-flat yellow-text deletion" href="#{destroy_all_api_todos_path(status:"done")}" onclick="clear_when_deletion();" data-remote="true" data-method="delete">&nbspYes</a>', 5000);
    });
    $("#clear-all-doing").click(function(){
      Materialize.toast('<span>Are you sure?</span><a class="btn-flat yellow-text deletion" href="#{destroy_all_api_todos_path(status:"doing")}" onclick="clear_when_deletion();" data-remote="true" data-method="delete">&nbspYes</a>', 5000);
    });
    $("#clear-all-listed").click(function(){
      Materialize.toast('<span>Are you sure?</span><a class="btn-flat yellow-text deletion" href="#{destroy_all_api_todos_path(status:"listed")}" onclick="clear_when_deletion();" data-remote="true" data-method="delete">&nbspYes</a>', 5000);
    });
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple To DOs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/x-icon" href="/favicon.ico"/>
</head>
<body class="grey lighten-5">
  <div class="container">
    <div class="todos">
      <%= yield %>
    </div>
  </div>
</body>
</html>